version: '3.8'

services:
  cloud-project-service:
    build:
      context: ./Java/cloud-project
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Asume que cloud-project corre en el puerto 8080
    env_file:
      - ./Java/cloud-project/.env
    networks:
      - fitec-network

  security-service:
    build:
      context: ./Java/security
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # Asume que security corre en el puerto 8081
    env_file:
      - ./Java/security/.env
    networks:
      - fitec-network

  orquestador-service:
    build:
      context: ./Orquestador/orquestador
      dockerfile: Dockerfile
    ports:
      - "8082:8082" # Asume que orquestador corre en el puerto 8082
    env_file:
      - ./Orquestador/orquestador/.env
    depends_on:
      - cloud-project-service
      - security-service
    networks:
      - fitec-network

networks:
  fitec-network:
    driver: bridge