version: '3.8'

services:
  nosql-api-service:
    image: davidho2030/backend-nosql-service:latest
    container_name: typescript_service_app
    ports:
      - "3000:3000"
    env_file:
      - ./nosql/.env
    networks:
      - fitec-network
    restart: unless-stopped

  employee-api-service:
    image: davidho2030/backend-employee-service:latest
    container_name: python_fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - ./employee/.env
    networks:
      - fitec-network
    restart: unless-stopped

networks:
  fitec-network:
    driver: bridge