spring:
  application:
    name: orquestador
  cloud:
    gateway:
      mvc:
        routes:
          - id: client-route
            uri: ${CLIENT_URL:http://localhost:8081}
            predicates:
              - Path=/client/**
            filters:
              - AddResponseHeader=X-Powered-By, FITEC Gateway Service

