spring:
  application:
    name: security-microservice

app:
  services:
    client:
      base-url: ${FASTAPI_URL:http://localhost:8000} # URL del ClientService (ajusta puerto/nombre)
    employee:
      base-url: ${SPRING_URL:http://localhost:8082} # URL del EmployeeService (ajusta puerto/nombre)

jwt:
  secret: AYlvhZBK/45ggInq5cb2Kz/eKeUopeGUxiUlk0WTZbue8w+jiCoz0MGsvO06bg94k/RNYLhzN6qTgWdV7UfL8Q==

server:
  port: 8081